# Generated by Django 4.1.7 on 2023-11-08 21:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("country", models.CharField(max_length=50, verbose_name="Country")),
                (
                    "sub_county",
                    models.CharField(max_length=50, verbose_name="Sub County"),
                ),
                ("ward", models.CharField(max_length=50, verbose_name="Ward")),
                (
                    "building_name",
                    models.CharField(max_length=100, verbose_name="Building Name"),
                ),
                ("floor", models.CharField(max_length=20, verbose_name="Floor")),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business_name",
                    models.CharField(max_length=50, verbose_name="Business Name"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Fintech", "Fintech"),
                            ("Learning Institution", "Learning Institution"),
                            ("Transport", "Transport"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                ("registration_date", models.DateTimeField()),
                ("business_age", models.IntegerField()),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="businesses",
                        to="business.location",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
    ]
