# Generated by Django 4.1.7 on 2023-11-09 07:12

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="county",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="County"
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="business_age",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="location",
            name="building_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Building Name"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="country",
            field=django_countries.fields.CountryField(
                default="KE", max_length=2, verbose_name="country"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="floor",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Floor"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="sub_county",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Sub County"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="ward",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Ward"
            ),
        ),
    ]
