# Generated by Django 4.1.7 on 2023-11-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0002_location_county_alter_business_business_age_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="registration_date",
            field=models.DateField(),
        ),
    ]
